In [19]:
config = {
    "model1": {
        "token": 'sentence1',
        "attn_dim": 256,
        "mlp_dim": 1024,
        "num_heads": 8,
        "num_layers": 6,
        "dropout": 0.1,
        "attn_dropout": 0.1
    },
    "model2": {
        "token": 'sentence2',
        "attn_dim": 256,
        "mlp_dim": 1024,
        "num_heads": 8,
        "num_layers": 6,
        "dropout": 0.1,
        "attn_dropout": 0.1
    }
}

In [7]:
# print(config['model1']['attn_dim'])
print(config.get('model1').get('attn_dim'))

256


In [22]:
tokens = [model['token'] for model in config.values()]
print(tokens)

['sentence1', 'sentence2']


# Check tokens

In [8]:
from transformers import AutoTokenizer
import torch
tokenizer_name = "facebook/bart-base"
tokenizer = AutoTokenizer.from_pretrained(tokenizer_name)
def tokenize_function(text):
    return tokenizer(text, padding=False, truncation=True, add_special_tokens=False)
tokens = tokenize_function('quantitative biology').get('input_ids')
for id in tokens:
    token = tokenizer.convert_ids_to_tokens([id])[0]
    print(f"ID: {id}, Token: {token}")


/home/lab2/anaconda3/envs/torch118/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/lab2/anaconda3/envs/torch118/lib/python3.9/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/lab2/anaconda3/envs/torch118/lib/python3.9/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


ID: 39064, Token: quant
ID: 26709, Token: itative
ID: 18004, Token: Ġbiology


In [24]:
from transformers import AutoTokenizer
import torch
tokenizer_name = "facebook/bart-base"
tokenizer = AutoTokenizer.from_pretrained(tokenizer_name)

tokens = []
for models in config:
    token = config.get(models).get('token')
    tokens.append(token)
print(tokens)

/home/lab2/anaconda3/envs/torch118/lib/python3.9/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


['sentence1', 'sentence2']


In [25]:
def tokenize_and_pad(tokens, max_length):
    tokenizer = AutoTokenizer.from_pretrained("facebook/bart-base")
    
    # 토큰화 및 패딩
    tokenized = [tokenizer.encode(token, add_special_tokens=False, 
                                  max_length=max_length, 
                                  padding='max_length', 
                                  truncation=True) 
                 for token in tokens]
    
    # 텐서로 변환
    return torch.tensor(tokenized)

In [27]:
result = tokenize_and_pad(tokens, 3)
print(result)

tensor([[19530,  4086,   134],
        [19530,  4086,   176]])


In [1]:
from torch import Tensor
import torch

In [14]:
def apply_mask(
    tensor: Tensor,
    mask: Tensor
) -> Tensor:
    return tensor + mask

In [17]:
original_tensor = torch.tensor([[1, 3, 1, 3, 1],
                                [5, 1, 1, 676, 1]])

new_mask = torch.tensor([[0., 0., 0., float('-inf'), float('-inf')],
                         [0., 0., float('-inf'), float('-inf'), float('-inf')]])

result = apply_mask(original_tensor, new_mask)
print(original_tensor)
print(result)

tensor([[  1,   3,   1,   3,   1],
        [  5,   1,   1, 676,   1]])
tensor([[1., 3., 1., -inf, -inf],
        [5., 1., -inf, -inf, -inf]])
